name: EslSpeakingCoach
options:
  bundleIdPrefix: com.akiraak
  deploymentTarget:
    iOS: "18.0"
  createIntermediateGroups: true
targets:
  EslSpeakingCoach:
    type: application
    platform: iOS
    sources:
      - EslSpeakingCoach
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_NSMicrophoneUsageDescription: "英会話練習であなたの発話を取得するためにマイクを使用します。"
        INFOPLIST_KEY_NSSpeechRecognitionUsageDescription: "発話を文字起こしして会話するために音声認識を使用します。"
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        SWIFT_VERSION: "6.0"
        TARGETED_DEVICE_FAMILY: "1"
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: "1.0"
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: N38G4DGA67
  EslSpeakingCoachTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - EslSpeakingCoachTests
    dependencies:
      - target: EslSpeakingCoach
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        SWIFT_VERSION: "6.0"
schemes:
  EslSpeakingCoach:
    build:
      targets:
        EslSpeakingCoach: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - EslSpeakingCoachTests
